name: Trigger auto deployment for recipeapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ development ]
    paths:
    - '**'
    - '.github/workflows/recipeapp-AutoDeployTrigger-7564f6cb-47cb-4f18-8a57-23ef5d589980.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.RECIPEAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RECIPEAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RECIPEAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src/Starbender.RecipeApp
          dockerfilePath: Dockerfile
          acrName: sbdev
          containerAppName: recipeapp
          resourceGroup: Dev
          imageToBuild: sbdev.azurecr.io/recipeapp:${{ github.sha }}


